### ISSUE TITLE
Use Dates everywhere

### ISSUE THREAD

**Issue by jarad** [jarad/WEPPR#22]
Functions that need updating to use Dates everywhere:

- [x] read_env ‼️
- [x] read_yld
- [x] read_cli
- [x] write_cli
- [ ] read_man ‼️
- [x] read_wb

**Comment by jarad** [comment]
Okay, to be clear. Use Dates in R objects, but files should continue to use whatever format the files have.

**Comment by kgulzina** [comment]
read_cli: bind and convert Day, Month, and Year columns into Dates column after extracting breakpoints. Otherwise, we lose information about breakpoints.

**Comment by kgulzina** [comment]
**read_env**: Year is provided as an integer starting with 1 and ending with n (# of simulation years given as an input in .run file). 

prop 1: leave as it is (user will match it with other dates)
prop 2: give starting year (e.g., taken from the climate input file) as an additional input

**Comment by kgulzina** [comment]
**write_env**: do we need it at all? It's hardcoded, hence not valid. The user can easily mess it up once she interchanges the columns' order. 

**todo**: need to extract `da`, `mo`, `year` from `date` column, and put them in a correct order

**Comment by kgulzina** [comment]
**write_cli**: the function is not written yet

**Comment by kgulzina** [comment]
**read_man**: too complicated (for now). Year index is given as in **read_env**.

**Comment by jarad** [comment]
**read_env**: convert year/mo/day into a Date column (remove year, mo, da)

**write_env**: convert Date column back into day, mo, year columns (remove Date)

**Comment by jarad** [comment]
@kgulzina I thought your most recent merge addressed this issue.
